// <auto-generated />
namespace MKEWasteDisposal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class names2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(names2));
        
        string IMigrationMetadata.Id
        {
            get { return "201802081732581_names2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
